{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: gospel-db-credentials
  namespace: {{ include "gospel.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install
  labels:
    app.kubernetes.io/name: {{ include "gospel.name" . }}
    helm.sh/chart: {{ include "gospel.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{ include "gospel.labels" . | nindent 4}}
type: Opaque
data:
  jdbc-url: {{ include "gospel.databaseJdbcUrl" . | b64enc }}
{{- end }}
