name: rabbitmq-go-sender
image: paer12/go-rabbitmq-sender
replicas: 1

envs:
  - variable: RABBIT_HOST
    secret: rabbit-credentials
    key: host
  - variable: RABBIT_USER
    secret: rabbit-credentials
    key: user
  - variable: RABBIT_PASS
    secret: rabbit-credentials
    key: password

service:
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
