apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  annotations:
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        {{- if .Values.envs }}
        env:
          {{- range .Values.envs }}
          - name: {{ .variable }}
            valueFrom:
              {{- if .secret }}
              secretKeyRef:
                name: {{ .secret }}
                key: {{ .key }}
              {{- end }}
          {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.containerPort }}
