name: video-api
replicas: 2
image: paer12/instagram-video-api:master

containerPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 1Gi

service:
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
