apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api
  namespace: { { .Values.namespace } }
spec:
  replicas: { { .Values.video-api.replicas } }
  selector:
    matchLabels:
      app: video-api
  template:
    metadata:
      labels:
        app: video-api
    spec:
      containers:
        - name: video-api
          image: {{ .Values.video-api.image }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DROPBOX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dropbox.secretName }}
                  key: {{ .Values.dropbox.accessTokenKey }}
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: gospel-jdbc-secret
                  key: jdbc-url
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: video-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: video-api
  ports:
    - port: 8080
      targetPort: 8080
