apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gospel-united
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Edens-Angel/argo-apps
    chart: gospel-united
    targetRevision: 0.1.0
    path: gospel-united
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gospel-united
  syncPolicy:
    syncOptions:
      - pruneLast=true
