apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit-consumer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Edens-Angel/argo-apps.git
    chart: clip-chooser
    targetRevision: HEAD
    helm:
      passCredentials: false
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: rabbit-project
  syncPolicy:
    syncOptions:
      - pruneLast=true
