apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit-go-consumer
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: go-rabbitmq/consumer
    repoURL: https://github.com/Edens-Angel/argo-apps
    targetRevision: HEAD
  destination:
    namespace: rabbit-project
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
