apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-go-sender
  namespace: argocd
spec:
  destination:
    namespace: rabbit-project
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: go-rabbitmq/sender
    repoURL: https://github.com/Edens-Angel/argo-apps
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
