apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit-sender
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Edens-Angel/argo-apps.git
    chart: rabbit-sender
    path: go-rabbitmq/sender
    targetRevision: 0.1.0
    helm:
      passCredentials: false
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: rabbit-project
  syncPolicy:
    syncOptions:
      - pruneLast=true
      - createNamespace=true
