apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbit-consumer
  namespace: argocd
spec:
  destination:
    namespace: rabbit-project
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet:
        tlas:
        - name: ""
          value: ""
    path: go-rabbitmq/consumer
    repoURL: https://github.com/Edens-Angel/argo-apps.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
