apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Edens-Angel/argo-apps
    chart: video-api
    targetRevision: 0.1.0
    path: gospel-united/video-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    # name: in-cluster
    server: https://kubernetes.default.svc
    namespace: gospel-united
  syncPolicy:
    syncOptions:
      - pruneLast=true

# Unable to create application: application spec for test is invalid: InvalidSpecError: Unable to generate manifests in gospel_united/video-api: rpc error: code = Unknown desc = `helm template . --name-template test --namespace gospel-united --kube-version 1.26 --values <path to cached source>/gospel_united/video-api/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: template: video-api/templates/deployment.yaml:22:27: executing "video-api/templates/deployment.yaml" at <.Values.resources.requests.cpu>: nil pointer evaluating interface {}.cpu Use --debug flag to render out invalid YAML