apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        env:
          - name: RABBIT_HOST
            valueFrom:
              secretKeyRef:
                name: rabbit-credentials
                key: host
          - name: RABBIT_USER
            valueFrom:
              secretKeyRef:
                name: rabbit-credentials
                key: user
          - name: RABBIT_PASS
            valueFrom:
              secretKeyRef:
                name: rabbit-credentials
                key: password
        ports:
        - containerPort: 8080
